# Site settings
title: Andrew Chen's Personal Website
description: A website that seeks to make me seems hireable, hopefully.
#baseurl: "/particle" # the subpath of your site, e.g. /blog
#url: "https://chennychenchen.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Andrew Chen
user_description: Skilled at Java Development, and web development.
user_title: Software Developer
email: andrew.chen923@gmail.com
twitter_username: lorem_ipsum
github_username: xChenny 
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
