# Site settings
title: Andrew Chen's Personal Website
description: A website that seeks to make me seems hireable, hopefully.
#baseurl: "/particle" # the subpath of your site, e.g. /blog
#url: "https://chennychenchen.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Andrew Chen
user_description: Hi. I'm a Computer Science Student at Stevens Institute of Technology in Hoboken, NJ. I like to code, modifiy my UNIX computers, play video games, and meet new people.
user_skills:  Java Development and Javascript web development.
user_title: Software Developer
email: andrew.chen923@gmail.com
github_username: xChenny 

# Google-analytics
google-analytics:
    id: "UA-99120164-1"

exclude: ['package.json', 'src' , 'node_modules']
